FROM golang:1.25 AS builder

WORKDIR /app

COPY . .

RUN go build -o server

FROM debian:bookworm-slim

COPY --from=builder /app/server /server
RUN apt-get update && \
    apt-get install -y ca-certificates && \
    update-ca-certificates && \
    rm -rf /var/lib/apt/lists/*

CMD ["/server"]
