package llm

import (
	"bytes"
	"context"
	"encoding/json"
	"log"
	"net/http"
	"time"
)

type LlmClient struct {
	baseUrl     string
	httpClient  *http.Client
	temperature float64
	chatSession []ChatSession
}

func NewLLM(baseUrl string, temperature float64) *LlmClient {
	return &LlmClient{
		baseUrl: baseUrl,
		httpClient: &http.Client{
			Timeout: 10 * time.Second,
		},
		temperature: temperature,
		chatSession: make([]ChatSession, 0),
	}
}

func (l *LlmClient) Chat(ctx context.Context, prompt Message, userId int64) (string, error) {
	log.Println("LLM client received prompt:", prompt)
	chatSession := l.getChatSessionByUserId(userId)
	if chatSession == nil {
		chatSession = l.createNewChatSession(userId)
	}
	l.addMessageToSession(chatSession, prompt)
	response, err := l.sendMessageLLM(ctx, chatSession.Messages)
	if err != nil {
		return "", err
	}
	log.Printf("Time to response %f ms - Token generated by LLM Server %d", response.Timing.PredictedMs, response.Usage.TokensUsage)
	if len(response.Choices) == 0 {
		return "No idea", nil
	}
	return response.Choices[0].Message.Content, nil
}

func (l *LlmClient) getChatSessionByUserId(userId int64) *ChatSession {
	for i, session := range l.chatSession {
		if session.UserId == userId {
			return &l.chatSession[i]
		}
	}
	return nil
}

func (l *LlmClient) createNewChatSession(userId int64) *ChatSession {
	newSession := ChatSession{
		UserId:   userId,
		Messages: l.initializeMemory(),
	}
	l.chatSession = append(l.chatSession, newSession)
	return &newSession
}

func (l *LlmClient) addMessageToSession(session *ChatSession, message Message) {
	session.Messages = append(session.Messages, message)
}

func (l *LlmClient) initializeMemory() []Message {
	return []Message{
		{Role: "system", Content: "Eres Maximiliano Guerrero, ingeniero en sistemas  y tienes 33 años, sos experto jugando videojuegos, ahora estas jugando demon souls"},
	}
}

func (l *LlmClient) sendMessageLLM(ctx context.Context, prompt []Message) (LLMResponse, error) {
	request := LLMRequest{
		Messages:    prompt,
		Temperature: l.temperature,
	}
	body, err := json.Marshal(request)
	if err != nil {
		return LLMResponse{}, err
	}
	req, err := http.NewRequestWithContext(ctx, "POST", l.baseUrl+"/v1/chat/completions", bytes.NewBuffer(body)) // Placeholder for actual request body
	if err != nil {
		return LLMResponse{}, err
	}
	req.Header.Set("Content-Type", "application/json")
	resp, err := l.httpClient.Do(req)
	if err != nil {
		return LLMResponse{}, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return LLMResponse{}, err
	}
	var chatResponse LLMResponse
	err = json.NewDecoder(resp.Body).Decode(&chatResponse)
	if err != nil {
		return LLMResponse{}, err
	}
	return chatResponse, nil
}
